### ISSUE TITLE
Google Recaptcha Issue

### ISSUE THREAD

**Issue by DigitalMachine** [excl-networks/strapi-plugin-ezforms#35]
Hi,
I've an not really good qualified issue within the ezforms plugin.
I've created the Google Recaptcha key but when I submit the form i get a generic 500 error in the frontend:
![Screenshot 2023-11-16 at 18 14 22](https://github.com/excl-networks/strapi-plugin-ezforms/assets/12749427/5cb4aa95-fe37-4e37-a80e-53f73da05c33)
and this is the strapi console error:
![Screenshot 2023-11-16 at 18 15 56](https://github.com/excl-networks/strapi-plugin-ezforms/assets/12749427/5aa1914a-432a-4121-9a61-a8254f8520f7)

Any suggestion is really appreciated!

**Comment by bennydv** [comment]
I have the same...

**Comment by dexterns88** [comment]
Same issue here

**Comment by dexterns88** [comment]
This is a log from 0.1.7 version. 
[2023-12-18 13:27:06.300] error: recaptcha_verify
[2023-12-18 13:27:06.301] error: [object Object]
[2023-12-18 13:27:06.301] error: undefined
[2023-12-18 13:27:06.302] http: POST /api/ezforms/submit (67 ms) 500

**Comment by luyendd** [comment]
I have same issue here on 0.1.7 version with Strapi 4.16.2. I've update logging a bit to find out what is the issue. Hope it helps.

[2024-01-03 01:10:20.610] error: recaptcha_verify
[2024-01-03 01:10:20.611] error: {"success":false,"error-codes":["timeout-or-duplicate"]}
[2024-01-03 01:10:20.611] error: undefined
[2024-01-03 01:10:20.618] http: POST /api/ezforms/submit/ (318 ms) 500

**Comment by luyendd** [comment]
After more investigation, the problem is reCAPTCHA tokens expire after two minutes following [docs](https://developers.google.com/recaptcha/docs/v3). Therefore, you need to execute (refresh) again when you send form and it's not error in library. 
Reference: https://stackoverflow.com/questions/55308499/i-got-timeout-or-duplicate-error-using-recaptcha-v3

**Comment by dexterns88** [comment]
Have several issue but solved at end.
My key is not valid because google have issue with service where you can delete site but captcha page stay and key is readable and work for FE but return issue on BE that site is deleted. 

Also config for ezform is not correct posted and I fixed also that part in project.  Changed FE to generate token on user submit. 

Now everything work fine.
